---
name: unit-test

on:
  push:
    paths:
      - 'plugin/**'
      - 'resources/**'
      - 'UM/**'
      - 'tests/**'
      - 'cmake/**'
      - 'conanfile.py'
      - 'CMakeLists.txt'
      - '.github/workflows/unit-tests.yml'
      - '.github/workflows/requirements-workflow.txt'
      - 'requirements-*.txt'
    branches:
      - main
      - master
      - dev
      - 'release/**'
      - 'CURA-*'
    tags:
      - '\d+.+d+*'
      - '[1-4].[0-9]+*'

  pull_request:
    paths:
      - 'plugin/**'
      - 'resources/**'
      - 'UM/**'
      - 'tests/**'
      - 'cmake/**'
      - 'conanfile.py'
      - 'CMakeLists.txt'
      - '.github/workflows/unit-tests.yml'
      - '.github/workflows/requirements-workflow.txt'
      - 'requirements-*.txt'
    branches:
      - main
      - master
      - dev
      - 'release/**'

env:
  CONAN_USER: ${{ secrets.CONAN_USER }}
  CONAN_PASS: ${{ secrets.CONAN_PASS }}

jobs:
  testing:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Uranium
        uses: actions/checkout@v3

      - name: Setup Python and pip
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.4'
          architecture: 'x64'
          cache: 'pip'

      - name: Prepare Conan and sip-build (Bash)
        if: ${{ runner.os != 'Windows' }}
        run: |
          pip install -r .github/workflows/requirements-workflow.txt
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          conan config install https://github.com/Ultimaker/conan-config.git -a "-b CURA-9177_Fix_CI_CD" -tf $HOME/.conan
          conan profile new default --detect
          conan user -p $CONAN_PASS -r ultimaker $CONAN_USER

      - name: Cache Conan local repository packages (Bash)
        uses: actions/cache@v3
        with:
          path: |
            $HOME/.conan/data
          key: ${{ runner.os }}-testing-uranium

      - name: Install dependencies
        run: |
          conan install . -pr:b cura_build.jinja -pr:h cura_release.jinja --build=missing --update -o enable_testing=True -o generate_venv=False

      - name: Upload the Dependency package(s)
        run: conan upload "*" -r ultimaker --all -c

      - name: Run Unit Test Uranium
        id: run-test
        run: |
          cd tests
          pytest

      - name: Publish Unit Test Results
        id: test-results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }}
        with:
          files: |
            **/*.xml

      - name: Conclusion
        run: echo "Conclusion is ${{ fromJSON( steps.test-results.outputs.json ).conclusion }}"
